### PR TITLE
Fix handling of Docker Hub images

### PR DESCRIPTION
**Pull request by mtrmac**
We now pay attention to the `Content-Type` header, but the returned value `application/vnd.docker.distribution.manifest.v1+prettyjws` was not recognized.

### CODE REVIEW

**Comment by mtrmac** [comment]
DO NOT MERGE this yet, I want to get to a working `skopeo` to validate this end-to-end first.

**Comment by runcom** [comment]
lgtm

**Comment by mtrmac** [comment]
Successfully tested locally against https://github.com/projectatomic/skopeo/pull/129 .

Please review again, added even more MIME type handling.

**Comment by runcom** [comment]
Still LGTM, you can merge this

**Comment by mtrmac** [comment]
:+1:

**Pull request merged**
