### PR TITLE
Release c/image v5.18.0

### PR DESCRIPTION
**Pull request by mtrmac**
Cc: @rhatdan @mheon

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mtrmac** [comment]
v5.18.0 tagged.

**Comment by vrothberg** [comment]
Don't we still need the SIF work for 4.0? Once that merges, we'd need to do another bump to 5.19.

**Comment by rhatdan** [comment]
Yup, but I would like to get everything tested now.

**Comment by vrothberg** [comment]
`go get github.com/containers/image/v5@main` would be enough for testing. I prefer less releases.

**Comment by rhatdan** [comment]
I was hoping to trigger dependabots, but they seem to be not working.

**Comment by mtrmac** [comment]
I’m not sure, but it seems to me that Dependabot is reluctant to upgrade from specific git commit pseudo-versions — and both Buildah and Podman use such a git commit reference.

**Comment by rhatdan** [comment]
I am not seeing them in common either.

**Pull request merged**
