### PR TITLE
pkg/docker/config: Deprecate GetUserLoggedIn

### PR DESCRIPTION
**Pull request by wking**
And refactor it to use `GetAuthentication`, which is just as convenient for callers.  This also removes the lookup differences between lookup logic between the two functions (e.g. `GetUserLoggedIn` used to ignore `DockerAuthConfig`).

Spun off from #588 [here][1] and #596.

[1]: https://github.com/containers/image/commit/480020500db2b2ca5ab850c6657a5df4d0b98904#diff-45d77e7dc3a84219aeb2aaad81b6bf96R298

### CODE REVIEW

**Comment by vrothberg** [comment]
Need to update containers/image to reflect the latest changes in containers/storage:
```
# github.com/containers/image/storage
storage/storage_image.go:735:55: not enough arguments in call to s.imageRef.transport.store.SetImageBigData
	have (string, string, []byte)
	want (string, string, []byte, func([]byte) (digest.Digest, error))
```

Code LGTM :+1: Thanks, @wking !

**Comment by mtrmac** [comment]
If we are doing this, I’d just remove the method; a `logrus.Warn` is not really wanted by the callers and it’s not actionably by end users.

I do need to check the earlier history of the code (notably https://github.com/containers/image/pull/333 ), the different handling and/or the `.docker` fallback mentioned in #596 might actually have been intentional — I can’t remember any more.

**Comment by wking** [comment]
> If we are doing this, I’d just remove the method...

I've pushed ee8c757 -> e64a79b, removing it.

> I do need to check the earlier history of the code (notably #333 ), the different handling and/or the `.docker` fallback mentioned in #596 might actually have been intentional...

I checked, and saw no discussion in either the commit message or pull request that motivated the different lookup logic.  You can obviously still check for yourself too ;).

**Comment by vrothberg** [comment]
@wking would you rebase, so we can merge it? Note that `podman-login` uses `GetUserLoggedIn()` and must be updated accordingly when we vendor containers/image over there (Cc @baude @mheon).

**Comment by rhatdan** [comment]
@wking ping...

**Comment by vrothberg** [comment]
I am updating this PR, so we can merge it.

**Comment by vrothberg** [comment]
Note to ourselves, we must update Podman (and Buildah?) afterward.

**Comment by vrothberg** [comment]
Fixes: https://github.com/containers/image/issues/596

**Comment by vrothberg** [comment]
LGTM, @mtrmac @rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by lio24** [comment]
I need window 10 to download docker on my PC

**Pull request merged**
