### PR TITLE
Update to Go 1.18

### PR DESCRIPTION
**Pull request by mtrmac**
We already depend on Go 1.18, due to:
```
vendor/github.com/rivo/uniseg/properties.go:func propertySearch[E interface{ [3]int | [4]int }](dictionary []E, r rune) (result E) {
```

So, actually update c/image proper, and take advantage of the new features.

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, Skope test isn't happy.  Might be a flake, but I'm unsure.

```
FAIL: sync_test.go:340: SyncSuite.TestYaml2Dir
Running skopeo sync --scoped --src yaml --dest dir /tmp/check-1124721257/18/registries.yaml /tmp/check-1124721257/18/dir1
sync_test.go:374:
    assertSkopeoSucceeds(c, "", "sync", "--scoped", "--src", "yaml", "--dest", "dir", yamlFile, dir1)
utils.go:67:
    c.Assert(err, check.IsNil, check.Commentf("%s", out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc00011a288), Stderr:[]uint8(nil)} ("exit status 1")
... time="2023-02-02T19:30:53-06:00" level=info msg="Processing repo" registry=k8s.gcr.io repo=pause
.
.
.
Copying blob sha256:9c075fe2c773108d2fe2c18ea170548b0ee30ef4e5e072d746e3f934e788b734
time="2023-02-02T19:30:56-06:00" level=fatal msg="Error copying ref \"docker://quay.io/quay/busybox:latest\": writing blob: happened during read: unexpected EOF"

**Comment by mtrmac** [comment]
Yes, `quay.io` … `unexpected EOF` are known infrastructure issues. I really need to finish #1816 …

**Comment by mtrmac** [comment]
Rebased, tests pass.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
