### PR TITLE
s/sigstore/lookaside/

### PR DESCRIPTION
**Pull request by mtrmac**
… per recent discussions.

<s>Only tested by that one updated unit test so far.</s>

### CODE REVIEW

**Comment by mtrmac** [comment]
Somewhat tested by https://github.com/containers/skopeo/pull/1701 , with integration tests using `lookaside` and system tests `sigstore`.

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by ChristianCiach** [comment]
Sorry, but what is "lookaside"? You seem to use it interchangeably with "sigstore". Is "sigstore" a bad word around here?

 > … per recent discussions.
 
 Which discussions?

**Comment by ktdreyer** [comment]
It's worth putting this important historical information into https://github.com/containers/image/blob/main/docs/signature-protocols.md

The deprecated `sigstore` setting is still widely used, eg. https://src.fedoraproject.org/rpms/containers-common/blob/rawhide/f/registry.redhat.io.yaml

**Comment by mtrmac** [comment]
`signature-protocols.md` primarily documents the inter-computer APIs and protocols, and _a bit_ the recommended end-user workflows. If the old fields should be documented, it would be in the reference documentation for the file, `containers-registries.d(5)`.

In principle, yes, documenting those fields is valuable; doing that without confusing new GitHub.com/sigstore users seems a bit hard and it would probably require a wider rewrite of that page.

**Comment by ktdreyer** [comment]
I took a look at rewriting the man page and gave up. Here's the change to edit Fedora's config file instead: https://src.fedoraproject.org/rpms/containers-common/pull-request/6

**Pull request merged**
