### PR TITLE
Namespaced credentials key enhancements

### PR DESCRIPTION
**Pull request by mtrmac**
Three major themes:
- Allow passing namespaced keys to `GetCredentials`, as strings (as opposed to `GetCredentialsForRef`. This is necessary because `reference.Named` can’t represent the `docker.io/vendor` parent namespace, see https://github.com/containers/common/pull/757 . It also simplifies the c/common/pkg/auth caller, it won’t need two different code paths.
- Fix `GetAllCredentials`, which was passing arbitrary JSON keys (URLs, namespaces) to `GetCredentials`. That sort of worked, but it doesn’t any more, with stricter `GetCredentials` format validation, and anyway it was doing the wrong thing if equivalent credential keys existed in multiple locations. `GetCredentials` now uses new-style normalized keys for registries; that could indirectly help https://github.com/containers/podman/pull/11430 by changing what clients send, but note that that code should probably still be doing its own normalization to handle old Docker clients.
- Tighten the key validation to reject tagged and digested values.

See individual commit messages for details. Most of the churn is in extending, updating, and simplifying tests (and in the column with changes done by `gofmt`; ignoring white space changes is recommended).

Warning: Only unit-tested; it might be worth prototyping the full set of changes with https://github.com/containers/common/pull/757 / a fixed https://github.com/containers/podman/pull/11430 against the Podman test suite.

### CODE REVIEW

**Comment by rhatdan** [comment]
@saschagrunert PTAL

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@mtrmac any update on this?

**Comment by mtrmac** [comment]
Rebased; based on https://github.com/containers/podman/pull/11538, I think this is ready for review/merge.

**Comment by mtrmac** [comment]
https://github.com/containers/podman/pull/11538 and https://github.com/containers/common/pull/763 pass; is this good to go?

**Pull request merged**
