### PR TITLE
Bump c/storage to v1.47.0

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says, this is in preparation of
Podman v4.6

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
I vendored the latest c/storage in here, and only the two go.* files changed.  Is that usual, or did I mess the vendor up?  Thoughts @vrothberg

**Comment by vrothberg** [comment]
> I vendored the latest c/storage in here, and only the two go.* files changed. Is that usual, or did I mess the vendor up? Thoughts @vrothberg

Yes, that's normal.  c/image does not maintain a `./vendor` directory as it's just a library.

But c/storage doesn't compile as is in c/image.

**Comment by mtrmac** [comment]
@TomSweeneyRedHat Please see #2011, that now includes an extra change that allows tests in c/image to pass.

**Comment by mtrmac** [comment]
#2011 , a superset, was merged.

**Comment by TomSweeneyRedHat** [comment]
@mtrmac TYVM!  I'm assuming then that we are going to close @nalind 's https://github.com/containers/storage/pull/1651

**Comment by mtrmac** [comment]
I don’t have a strong opinion on https://github.com/containers/storage/pull/1651 ; I think it’s reasonable to argue that it is still a necessary regression fix.

**Pull request closed without merging**
