### PR TITLE
bump containerd to v1.5.4

### PR DESCRIPTION
**Pull request by lsm5**
`go get github.com/containerd/containerd@v1.5.4`

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@vrothberg @mtrmac @rhatdan PTAL

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

Please link to the sec alert (https://github.com/containers/image/security/dependabot/go.mod/github.com%2Fcontainerd%2Fcontainerd/open) in future PRs/commits to preserve the intention and context.

**Review by mtrmac — APPROVED** [review]
LGTM. Thanks!

**Comment by lsm5** [comment]
> > Please link to the sec alert (https://github.com/containers/image/security/dependabot/go.mod/github.com%2Fcontainerd%2Fcontainerd/open) in the future PRs/commits to preserve the intention and context.
> 
> FWIW, the 1.5.1 → 1.5.4 change does not affect any subpackages c/image depends on (looking at Skopeo’s `vendor` subdirectory,
> 
> ```
> vendor/modules.txt:# github.com/containerd/containerd v1.5.1
> vendor/modules.txt:github.com/containerd/containerd/errdefs
> vendor/modules.txt:github.com/containerd/containerd/log
> vendor/modules.txt:github.com/containerd/containerd/platforms
> ```
> 
> )
> 
> Updating to silence the alert, and possibly to help unaware c/image consumers, is still worth it, IMHO.

let me update commit message.

**Comment by mtrmac** [comment]
> Please link to the sec alert (https://github.com/containers/image/security/dependabot/go.mod/github.com%2Fcontainerd%2Fcontainerd/open) in the future PRs/commits to preserve the intention and context.

FWIW, the 1.5.1 → 1.5.4 change does not affect any subpackages c/image depends on (looking at Skopeo’s `vendor` subdirectory,
```
vendor/modules.txt:# github.com/containerd/containerd v1.5.1
vendor/modules.txt:github.com/containerd/containerd/errdefs
vendor/modules.txt:github.com/containerd/containerd/log
vendor/modules.txt:github.com/containerd/containerd/platforms
```
)

Updating to silence the alert, and possibly to help unaware c/image consumers, is still worth it, IMHO.

**Comment by lsm5** [comment]
So, would you prefer I go the `Generate an automated security update`? Is that supposed to create a PR by itself? Last time I tried the same thing on podman to update buildah, it didn't seem to do anything, but maybe cause the issue was already fixed and the update didn't check for timestamps?

Or should I just be copying the Details in the advisory to the commit message?

**Comment by lsm5** [comment]
it's scary that github allows people to edit other people's comments. I myself have done that to maybe a couple of comments mistakenly in the past

**Comment by vrothberg** [comment]
I have no preference but I think it's important to leave breadcrumbs in the commit message.

**Comment by vrothberg** [comment]
> it's scary that github allows people to edit other people's comments. I myself have done that to maybe a couple of comments mistakenly in the past

I _think_ only admins can do that; presumably to address verbal abuse and such. With great power comes great responsibility :)

**Comment by mtrmac** [comment]
> So, would you prefer I go the `Generate an automated security update`? Is that supposed to create a PR by itself?

I have no experience with that and I don’t have a strong opinion.

> Or should I just be copying the Details in the advisory to the commit message?

I think at least _linking_ to the advisory, to record
1. the reason we are doing this, when we have a specific one, as opposed to just a generic “bump dependencies from time to time” PR
2. possibly the evidence we have that this is not actually relevant to users

can be very useful for any future inquiries. I don’t think a full copy&paste is necessary.

As for where to link to it, I’d say a commit message is slightly preferred to a PR, but the difference is very slim (basically only in case GitHub went away), so the discussion above is sufficient for me.

(@vrothberg , up to you whether to merge as is or update the commit message.)

**Comment by mtrmac** [comment]
> it's scary that github allows people to edit other people's comments. I myself have done that to maybe a couple of comments mistakenly in the past

(Yeah; I have tended to do that to have a Markdown source to copy&paste so that I can quote accurately, but now that there’s a dedicated quote functionality, it’s a bad habit and I need to do better. I apologize again.)

**Comment by lsm5** [comment]
I went ahead with a copy-paste of the advisory details. And looks like github makes advisory IDs clickable too. PTAL.

**Review by vrothberg — COMMENTED** [review]
LGTM, thank you @lsm5 !

**Review by mtrmac — APPROVED** [review]
LGTM again. Thanks!

**Comment by lsm5** [comment]
@mtrmac @vrothberg what release branches do we currently support? I can add PRs for those too.

**Comment by vrothberg** [comment]
> @mtrmac @vrothberg what release branches do we currently support? I can add PRs for those too.

I have no clue but since we're technically not impacted I suggest to just be reactive in case someone or some tool complains.

**Comment by lsm5** [comment]
> > @mtrmac @vrothberg what release branches do we currently support? I can add PRs for those too.
> 
> I have no clue but since we're technically not impacted I suggest to just be reactive in case someone or some tool complains.

sgtm, thanks

**Pull request merged**
