### PR TITLE
Cirrus: Grab skopeo from main branch

### PR DESCRIPTION
**Pull request by cevich**
Ref: https://github.com/containers/skopeo/issues/1282

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by cevich** [comment]
Well :hankey: this is going to depend on changes in [containers/skopeo](https://github.com/containers/skopeo)...

**Comment by cevich** [comment]
...okay, once https://github.com/containers/skopeo/pull/1328 is merged, a simple re-run should clear up the failures.

**Comment by TomSweeneyRedHat** [comment]
LGTM
once https://github.com/containers/skopeo/pull/1328 goes through.

**Comment by cevich** [comment]
Pressed re-run button just now.

**Comment by mtrmac** [comment]
Thanks!

**Pull request merged**
