### PR TITLE
[release-5.26] Bump c/storage to 1.48.1, c/image to 5.26.2 and 5.26.3-dev

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Bump c/storage to 1.48.1
Bump c/image to 5.26.2
Bump c/image to 5.26.3-dev
 
in preparation for RHEL 8.9/9.3 final freeze

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

But I don´t think this bump is necessary.  Consumers of c/storage can just bump c/storage directly.  So we only need to bump skopeo, buildah and podman and can ignore image and common.

**Comment by TomSweeneyRedHat** [comment]
@vrothberg @rhatdan @mtrmac could I have a LGTM (or two) and merge on this please?  This is part of this weeks vendor dance for RHEL 8.9/9.3

**Comment by vrothberg** [comment]
@TomSweeneyRedHat please see my comment above

**Comment by mtrmac** [comment]
@TomSweeneyRedHat @vrothberg I don’t care either way. It’s extra work and it’s not _necessary_ for the consumers, but dependency-only minor version bumps are not unheard of, almost all the work has been already done, and keeping the process consistent is a bit valuable to help guide future cases.

I’ll leave at least an hour more for discussion in case there are other arguments — tentatively I’m thinking of merging this.

**Comment by vrothberg** [comment]
It won't hurt too merge, so I'll go ahead.  My main point is that we don't need it technically and that it makes the vendor dance longer than needed.

**Comment by TomSweeneyRedHat** [comment]
Thanks @mtrmac and @vrothberg .  I'm admitedly a little OCD about this, but I like to have the numbers all fresh at the start of a new RHEL release.  Thanks for putting up with the quirks.

**Pull request merged**
