### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by mtrmac**
These are a few trivial cleanups collected while working on #33. Merges/includes #33, I will rebase as necessary.

Test-heavy to the point of ridiculousness, rationale is https://github.com/containers/image/pull/39#issuecomment-233105404 .

### CODE REVIEW

**Comment by runcom** [comment]
> Test-heavy to the point of ridiculousness, rationale is #39 (comment) .

never enough about testing :smile:

**Comment by mtrmac** [comment]
Rebased, ready for review (but by no means urgent).

**Comment by runcom** [comment]
+1 feel free to merge

**Comment by mtrmac** [comment]
:+1:

**Pull request merged**
