### PR TITLE
manifest update: consider that storage lies

### PR DESCRIPTION
**Pull request by vrothberg**
The manifests in containers storage lie since the layers are stored
uncompressed while, in some cases, being displayed as compressed in
the manifest.

Consider this case when updating the manifest to avoid immediate
errors.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
> but the design issue is really generic (affecting decompression/recompression) just as well. 

(Arguably storage should be primarily storing a manifest that corresponds to the actual uncompressed layers, and recording the original one in as an optional attachment, aka `ImageSource.GetOriginalManifest` of #288; then `LayerInfosForCopy` should not exist and all of this would go away. But we are definitely not doing that kind of work right now.)

**Comment by vrothberg** [comment]
Ack! Will update and add functions for v2 and OCI with comments. In the meantime, I opened https://github.com/containers/skopeo/issues/734 so we could verify at least parts of the affected code paths.

**Comment by vrothberg** [comment]
Updated. @mtrmac, feel free to take over this PR in case something's missing. I'll be leaving the keyboard in a bit.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
