### PR TITLE
Copy: Support MIME type changes, two-step updates

### PR DESCRIPTION
**Pull request by mtrmac**
See #1138 for the exploratory discussion, and commit messages for details.

### CODE REVIEW

**Comment by jomeier** [comment]
Hi, any progress on that?

**Comment by rhatdan** [comment]
@mtrmac This needs a rebase I believe.
@vrothberg PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by mtrmac** [comment]
Not just a rebase, this is an alternative to #1138 and should, if pursued, revert/replace that.

**Comment by rhatdan** [comment]
Ok let's close this and concentrate on whether or not the merged fix solves the issue.

**Comment by mtrmac** [comment]
I need _some_ way to track investigating this avenue.

**Comment by mtrmac** [comment]
Revisiting, nowadays the “MIME type → algorithm” lookup, `compressionEditsFromBlobInfo`, has another caller.

This logic still should not exist in the generic code, but the benefit of structuring the code so that it is never actually necessary is no longer applicable, so, closing this.

#2467 carries forward mostly-unrelated small cleanups from this PR.

**Pull request closed without merging**
