### PR TITLE
Fix vendor.conf protobuf repository url

### PR DESCRIPTION
**Pull request by nlewo**
Fixes: #372
Signed-off-by: Antoine Eiche <lewo@abesis.fr>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM and Thanks for the contribution!

**Comment by rhatdan** [comment]
@nlewo Could you rebase
@mtrmac PTAL

**Comment by mtrmac** [comment]
The same change has actually been merged in the meantime in #305.

**Pull request closed without merging**
