### PR TITLE
Trivial zstd:chunked-related cleanups

### PR DESCRIPTION
**Pull request by mtrmac**
… filed as a separate PR to simplify future “real” work.

Overall, should not change behavior. See individual commit messages for details.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
/lgtm

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
I'm going to push the Shiny Green Button as the /lgtm doesn't seem to be doing it here.

**Pull request merged**
