### PR TITLE
Add check sys != nil

### PR DESCRIPTION
**Pull request by QiWang19**
Add check sys != nil

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Review by mtrmac — APPROVED** [review]
LGTM.

How bad is this? Enough to make a new release?

**Review by vrothberg — COMMENTED** [review]
A late LGTM

I would love the commit message to be a bit more descriptive and explain when this can happen or link to an issue or BZ.

**Comment by QiWang19** [comment]
> LGTM.
> 
> How bad is this? Enough to make a new release?

This fails the CI when I bump the c/image in crio... https://app.circleci.com/pipelines/github/cri-o/cri-o/7355/workflows/d4d51591-46b9-4b2d-aed1-28fb7f0ff2af/jobs/118659
Can this make a new release?

**Comment by mtrmac** [comment]
For the record, #1130 .

**Pull request merged**
