### PR TITLE
[RFC Do not merge] Add copy.Options.LayerSubset.

### PR DESCRIPTION
**Pull request by mtrmac**
For now just to get an idea of what this would take…

FIXME: Should come with more warnings.

This is needed to allow the Python code in atomic to only download the subset of layers which is not already available locally, while still verifying signatures and validating layer digests (per discussion in
https://github.com/projectatomic/skopeo/pull/242 ).

### CODE REVIEW

**Comment by runcom** [comment]
makes sense

**Comment by mtrmac** [comment]
@runcom @guiseppe I will not be finishing this _this_ week; feel free to take this over if you like the approach and there is time pressure, or we can turn this into a Trello card to be finished later.

**Comment by runcom** [comment]
I don't think we're in any hurry here. We're not going to drop `skopeo layers` any soon (at least till we have something like this).

**Comment by mtrmac** [comment]
This should no longer be necessary with #228. Can I close this PR, or am I missing anything?

**Comment by mtrmac** [comment]
Assuming this is superseded by #228 , closing.

**Pull request closed without merging**
