### PR TITLE
copy.Copy: progressbars: set correct output

### PR DESCRIPTION
**Pull request by vrothberg**
Set the output of the progress bars and the progress pool, respectively,
to the specified io.Writer passed through the copy options.  Otherwise,
the output will be printed to Stdout breaking users which are parsing
the output and expect the progress bars to be printed on Stderr.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Please, do not merge this until we are sure it's fixing the flakes over at Buildah (https://github.com/containers/buildah/pull/1244/).

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
It is fixing the flakes :) The current failure relates to buildah's blobcache behaving slightly different with pzgip.

**Comment by runcom** [comment]
LGTM

**Pull request merged**
