### PR TITLE
Fix license reference in README.md

### LINKED ISSUE #479: Clearer licensing statement
The licensing statement at the end of the [README.md](https://github.com/containers/image#license) is confusing, because it's unclear which license is meant with 'ASL 2.0'. Looking at the [LICENSE file](https://github.com/containers/image/blob/master/LICENSE) I concluded that it's a not so wide spread acronym for Apache Software License (or something similar).

I'd rather explicitly state the license full name ("Apache License 2.0") and it would be also helpful to provide the [SPDX short identifier](https://spdx.org/licenses/Apache-2.0.html)("Apacher-2.0").

### PR DESCRIPTION
**Pull request by Silvanoc**
Signed-off-by: Silvano Cirujano Cuesta <silvano.cirujano-cuesta@siemens.com>

Closes #479

### CODE REVIEW

**Comment by mtrmac** [comment]
👍 Thanks!

**Comment by mtrmac** [comment]
@runcom PTAL, this one would benefit from going through the full formal approval for maximum clarity.

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Pull request merged**
