### PR TITLE
[release-5.19] vendor c/storage and cut v5.19.4

### PR DESCRIPTION
**Pull request by vrothberg**
Vendor c/storage to backport fixes for https://bugzilla.redhat.com/show_bug.cgi?id=2072452.
Also bump the version.

@TomSweeneyRedHat @mtrmac PTAL

### CODE REVIEW

**Comment by vrothberg** [comment]
Note that this PR is not needed as c/storage can be bumped directly in podman but I was asked to.

**Review by mtrmac — APPROVED** [review]
Sure.

Will you tag the release, or shall I do that later today?

**Comment by vrothberg** [comment]
I can do tag, no problem, thanks.

**Comment by vrothberg** [comment]
https://github.com/containers/image/releases/tag/v5.19.4

**Pull request merged**
