### PR TITLE
Fix typos and unclear wording in comments

### PR DESCRIPTION
**Pull request by mtrmac**
This fixes issues pointed out in #266.

### CODE REVIEW

**Comment by runcom** [comment]
Wondering if test failure is legit

**Comment by mtrmac** [comment]
> Wondering if test failure is legit
`Error: Timeout waiting for test registry to become available`, disappeared after a few reruns.

But we seem to be starting/stopping the registry for every test, which seems excessive. I’ll look into it.

**Comment by runcom** [comment]
LGTM (I'm fine following up for that flaky)

**Comment by mtrmac** [comment]
:+1:

**Pull request merged**
