### PR TITLE
support API with DeleteImage(oci image)

### PR DESCRIPTION
**Pull request by Lingerhk**
I have finished the DeleteImage interface when delete oci format image.
The problem occurs when I use skopeo to delete a local oci image: `skopeo delete oci:img:tag`, It return a error of "Deleting images not implemented for oci: images".

### CODE REVIEW

**Comment by rhatdan** [comment]
@Lingerhk Tests are failing?

**Comment by yihuan-Guo** [comment]
> @Lingerhk Tests are failing?

I'am not sure why this testing failed, but I can compiled passing.

**Comment by mtrmac** [comment]
The `validate` test requires https://github.com/containers/image/blob/master/CONTRIBUTING.md#sign-your-prs . The other test contains a fairy clear error message.

(The feature is definitely welcome, but I haven’t really read the PR code yet.)

**Comment by mtrmac** [comment]
I’m afraid we can’t accept contributions with unclear copyright status.

**Pull request closed without merging**
