### PR TITLE
Make DefaultPolicyPath a public interface

### PR DESCRIPTION
**Pull request by rhatdan**
We want to tell users to install or edit /etc/config/policy.path
so we need to expose the interface from containers/image.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac @runcom @vrothberg PTAL

**Comment by mtrmac** [comment]
> We want to tell users to install or edit /etc/config/policy.path so we need to expose the interface from containers/image.

Is this talking about an already-existing file (“we’ve used configuration loaded from `$loaded.path`”, in which case the path could be a value reported only after/while loading it), or does it need to also support installing a new one when loading a file fails?

I’d like to make it … not easy … to write independent parsers / interpreters of the policy, and making the default path is one small obstacle to that.  I realize that this is probably untenable long-term, still, worth at least asking.

**Comment by mtrmac** [comment]
If this is about https://github.com/containers/buildah/issues/1307 , couldn’t that just call `signature.DefaultPolicy()` and report if it fails?

**Comment by rhatdan** [comment]
Ok if we call that we should get an error back like:

 open /etc/containers/policy.conf: no such file or directory

Which probably is enough.

**Pull request closed without merging**
