### PR TITLE
README.md: remove todo

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@mtrmac PTAL - we'll re-iterate on each components once we define better our own types, I've also added a `Main concepts` section where we could explain the abstractions we have in place in the library. I believe we can merge this as-is now and as said re-iterate.

**Comment by jonboulle** [comment]
IMHO the sections you've added should be covered by the respected package's godocs - https://godoc.org/github.com/containers/image - I would advise against duplicating that info in the README

**Comment by runcom** [comment]
Make sense, we should probably reiterate on our main concept though.

**Comment by runcom** [comment]
Or maybe not, it's just a library and the interfaces shoukd explain them. I'll rework this patch to remove the components section altogether and just add the make test.

**Comment by runcom** [comment]
PTAL @mtrmac

**Comment by mtrmac** [comment]
:+1: why not.

**Comment by mtrmac** [comment]
…actually, this is a clear improvement: Keeping todo items as Github issues would be better structured and allow discussion.

**Comment by runcom** [comment]
lgtm

**Pull request merged**
