### PR TITLE
storage: PutBlobWithOptions: fix EmptyLayer logic

### PR DESCRIPTION
**Pull request by vrothberg**
As it turned out in containers/podman/pull/10700,
containers/image@db5fb6e introduced a bug in the put-blob logic where
the empty-layer info was used for all blobs that the worker will commit
to storage.

Fix the bug by correctly storing the empty-layer information for each
blob separately and use that inside the worker.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Podman test PR https://github.com/containers/podman/pull/10708

**Comment by vrothberg** [comment]
@mtrmac @rhatdan PTAL

The bug boils down to:
```
func (..., emtpyLayer bool) {
....
for ... := range otherLayers {
    commitAnotherLayer(emptyLayer)
}
}
```

**Review by mtrmac — APPROVED** [review]
LGTM. Thanks!

**Comment by flouthoc** [comment]
@mtrmac @vrothberg Could we please cut a new release since 5.13.0 is still not propagated into podman.

**Comment by mtrmac** [comment]
@flouthoc #1263 .

**Comment by flouthoc** [comment]
@mtrmac Thanks :smiley:  I guess we would also need to bump `containers/common` with propagated `images` as vendor.

**Comment by mtrmac** [comment]
In principle, but as long as the top-level consumers use the fixed version, the dependency of the library doesn’t quite matter. Dependabot will pick the update eventually in c/common, but I don’t think it’s urgent.

**Comment by flouthoc** [comment]
@mtrmac ah yes my bad.

**Comment by vrothberg** [comment]
I think it's perfectly fine to vendor commits (in contrast to a tag/version) during development.  So we can do a `go get github.com/containers/image/v5/@commit` if we need a specific new feature or fix in the consumers of c/image. We just need to make sure that we have a release once Podman, Buildah and co. get a new release.

**Pull request merged**
