### PR TITLE
Update containers-registries.conf.5.md

### PR DESCRIPTION
**Pull request by TerraTech**
Fix the "prefix" formatting to make the list legible.

### CODE REVIEW

**Comment by TerraTech** [comment]
Seems that Github's markdown list spacing leaves a bit to be desired.  Am I missing something to make the list single spaced?

**Review by vrothberg — COMMENTED** [review]
Thanks!

Changes LGTM but you need to sign your commit to pass CI. `git commit -s --amend` will do the trick.

Could you also update the commit message and state that this change is intended to make the GitHub markdown render correctly?  The man pages were rendered correctly.

**Comment by TerraTech** [comment]
Will do.  I had only done a simple edit/fork and submitted the resultant patch from the fork all via github's builtin facilities.

**Comment by TerraTech** [comment]
Done - pls review.

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks for contributing @TerraTech !

@rhatdan @lsm5 PTAL

**Comment by vrothberg** [comment]
Note that the CI failure is us hitting the Docker rate limit. Given it's a doc only change, we can merge.  Looking forward to the Cirrus migration.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
