### PR TITLE
[release-5.31] Bump c/image to v5.31.1-dev

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
I managed to set main to v5.31.1-dev rather than the release-5.31 branch.  I've corrected main with #2430 and this will correct the release-5.31 branch

### CODE REVIEW

**Review by mtrmac — APPROVED** [review]
Thanks!

**Comment by mtrmac** [comment]
Does the new c/image branch need CI automation set up? Cc: @cevich

**Comment by mtrmac** [comment]
Never mind, the tests did run already.

**Comment by cevich** [comment]
Thanks for pinging me.  Just to close the loop, it looks like we do have a Cirrus-Cron setup on this repo.  So the new branch needs to be [added into the rotation](https://cirrus-ci.com/settings/repository/6429752730058752).  I've done that, but please feel free to double-check we're not missing any other branches (or should retire any).

**Pull request merged**
