### PR TITLE
docker: remove reference pkg

### PR DESCRIPTION
**Pull request by runcom**
get rid of _forked_ Docker

### CODE REVIEW

**Comment by runcom** [comment]
I don't remember why it wasn't working but to my testing now skopeo works with this tree w/o the forked Docker code so..

**Comment by runcom** [comment]
lgtm

**Comment by mtrmac** [comment]
FWIW `git` history says commit a09019661e45e505cfebc7c91f876ad67ad660f1 (”EDIT FROM DOCKER/DOCKER TO NOT IMPORT IMAGE.V1”) and we had 429a4b0aec0eb6963e91fa6da8683e4d6c49c0da (“Do not drop the underlying error message when a Docker reference is invalid”). Both seem acceptable to lose.

I am fine with this (pending tests), but wouldn’t `skopeo` also need updating to vendor `docker/docker/reference` now?

**Comment by runcom** [comment]
Yes I'll take care of that

**Comment by runcom** [comment]
(missing a LGTM)

**Comment by runcom** [comment]
https://github.com/containers/image/commit/429a4b0aec0eb6963e91fa6da8683e4d6c49c0da we can push this upstream

**Comment by mtrmac** [comment]
> (missing a LGTM) 

LGTM

> Yes I'll take care of that

Please merge ~in sync with the skopeo update, then.




[Approved with PullApprove](https://pullapprove.com/containers/image/pull-request/32/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=containers/image)

**Comment by runcom** [comment]
I'll go ahead with https://github.com/projectatomic/skopeo/pull/133 before this change in skopeo

**Pull request merged**
