### PR TITLE
Drop genericImage.getLayer

### PR DESCRIPTION
**Pull request by mtrmac**
There are no users left after #17.

### CODE REVIEW

**Comment by runcom** [comment]
LGTM 

Not sure why the build is failing (specifically it seems to hit a timeout when cloning openshift?!)

**Comment by mtrmac** [comment]
> Not sure why the build is failing (specifically it seems to hit a timeout when cloning openshift?!) 

I don’t know why, but such failures do happen from time to time. Re-pushed to have the test run again.

(FWIW preparing an publishing a base image instead of rebuilding it on each Travis test, and having each test take 20 minutes, is looking increasingly attractive to me. I can’t work on it right now though, perhaps in a month or so…)

**Comment by runcom** [comment]
> (FWIW preparing an publishing a base image instead of rebuilding it on each Travis test, and having each test take 20 minutes, is looking increasingly attractive to me. I can’t work on it right now though, perhaps in a month or so…)

that's amazing!

BTW, feel free to LGTM here and merge :+1:

**Comment by mtrmac** [comment]
:+1:

**Pull request merged**
