### PR TITLE
blobinfocache: sync via mutex

### PR DESCRIPTION
**Pull request by vrothberg**
Serialize method calls via a mutex to avoid concurrent accesses to the
map leading to panics.

Fixes: https://github.com/containers/libpod/issues/2420
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@mtrmac @rhatdan @mheon PTAL

**Comment by vrothberg** [comment]
@mtrmac @rhatdan "Please update billing information for containers" what shall we do with the pullapprove?

**Comment by rhatdan** [comment]
LGTM
@nalind PTAL
@vrothberg How much is this going to hurt performance?

**Comment by vrothberg** [comment]
> @vrothberg How much is this going to hurt performance?

This should have a low impact. I count three calls in dockerImageDest and one in dockerImageSrc (conditional). And two in storage.

**Comment by giuseppe** [comment]
LGTM

**Comment by mtrmac** [comment]
(ACK, for the record.)

> > @vrothberg How much is this going to hurt performance?
> 
> This should have a low impact. I count three calls in dockerImageDest and one in dockerImageSrc (conditional). And two in storage.

Typically, zero — we should be using an on-disk BoltDB cache. This implementation is used only if the on-disk cache is not accessible (and the debug log says why, search for “using a memory-only cache”).  And even with this mutex the memory cache is strictly faster than the BoltDB one (which also involves two mutexes on every access, in addition to file accesses including file locks).

**Comment by mtrmac** [comment]
> @mtrmac @rhatdan "Please update billing information for containers" what shall we do with the pullapprove?

Just drop it, I think; we haven’t been _ever_ seriously enforcing the configured “two independent reviews” configuration, at best it included one self-review.

**Comment by vrothberg** [comment]
> > @mtrmac @rhatdan "Please update billing information for containers" what shall we do with the pullapprove?
> 
> Just drop it, I think; we haven’t been _ever_ seriously enforcing the configured “two independent reviews” configuration, at best it included one self-review.

Sounds good. Thanks, @mtrmac !

**Pull request merged**
