### PR TITLE
[release-5.10] fix docker.GetDigest docker.makeRequestToResolvedURL docker.getExtern…

### PR DESCRIPTION
**Pull request by haircommander**
…alBlob socket leak

cherry-pick of 05fa7577cb8647a8d56db357ebe82c37856e946d

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
this is needed for cri-o release 1.20

**Comment by mrunalp** [comment]
LGTM 
@vrothberg @rhatdan @mtrmac ptal

**Comment by TomSweeneyRedHat** [comment]
LGTM
test issues are due to Docker pull rate limits.

**Comment by vrothberg** [comment]
Late LGTM.  Please make sure to add a BZ reference to backports.  This branch is technically frozen and RHEL policies require us to justify all backport.

**Comment by haircommander** [comment]
related to https://bugzilla.redhat.com/show_bug.cgi?id=1953071

**Pull request merged**
