### PR TITLE
Fulcio signing implementation

### PR DESCRIPTION
**Pull request by mtrmac**
This adds API to use Fulcio-generated short-lived certificates.

Depends on #1784 .

I still need to test one part but it seems broadly ready.

I don’t feel _too_ confident about the API, but it seems close enough, and we can always add more option functions, or a new `signature/sigstore/fulciov2` package (still operating on `signature/sigstore/internal.Signer`)

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by mtrmac** [comment]
Rebased, ready for review.

**Comment by mtrmac** [comment]
Oops, still one path to try.

**Comment by mtrmac** [comment]
(Adding unit tests tracked in #1601.)

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Review by vrothberg — APPROVED** [review]
LGTM

**Pull request merged**
