### PR TITLE
Fix the RootForImplicitAbsolutePaths case of getPathToAuth

### LINKED ISSUE #471: /run/$UID/containers vs. /run/containers/$UID vs /run/user/… in pkg/docker/config
In `getPathToAuth` (https://github.com/containers/image/blob/5144ced37a1b21b63c6ef605e56811e29a687528/pkg/docker/config/config.go#L146 ) , the `sys.RootForImplicitAbsolutePaths != ""` and `runtimeDir == ""` cases construct the `/run/*` path differently (`containers/$UID` vs. `$UID/containers`); and the commit message talks about `/run/usr` while the commit drops the `/run/user` prefix.

AFAICT from quickly checking the conversations in https://github.com/containers/image/pull/424 and https://github.com/projectatomic/libpod/issues/427 , `/run/containers/$UID` seems to be the intent.

### PR DESCRIPTION
**Pull request by mtrmac**
Fixes #471 , adds unit tests, and cleans up the constants a bit.

See individual commit messages for more details.

@umohnani8 (@runcom ) PTAL

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
This will make investigation work easier too later.  Nice fix.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@runcom PTAL

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
