### PR TITLE
copy: wait for progress bars before cleaning up

### PR DESCRIPTION
**Pull request by vrothberg**
Wait for all progress bars to finish before cleaning up.  In case of
errors, clean up immediately.  Waiting for all bars closes a race
condition where a bar might not be rendered before being cleaned up.

Fixes: #1013
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@mtrmac, I'd love to backport it into Podman 2.0 as we're cutting a new release today.

**Comment by vrothberg** [comment]
Looks like a dead lock caught in the tests

**Comment by TomSweeneyRedHat** [comment]
and now a rebase is needed @vrothberg

**Comment by vrothberg** [comment]
Closing as I won't find time to tackle it before my PTO.

**Pull request closed without merging**
