### PR TITLE
docker: fork docker/docker/reference pkg

### PR DESCRIPTION
**Pull request by runcom**
As discussed into https://github.com/containers/image/issues/99

@mtrmac PTAL, making a PR for skopeo check if everything's ok over there. I'll check with projectatomic/docker#200 as well.

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
This seems to be working fine in projectatomic/docker#200

**Comment by mtrmac** [comment]
Seems fine, but uncertain with tests failing.

**Comment by mtrmac** [comment]
https://github.com/projectatomic/skopeo/pull/229#issuecomment-252866898 , though:

> This seems to pull in way too much, including a pretty big part of `docker/distribution`.  IIRC in the earlier instance of forking `docker/docker/reference` we have eliminated the uses of `docker/docker/image` to not pull in so much.

**Comment by runcom** [comment]
> his seems to pull in way too much, including a pretty big part of docker/distribution. IIRC in the earlier instance of forking docker/docker/reference we have eliminated the uses of docker/docker/image to not pull in so much.

I can definitely do that :+1:

**Comment by runcom** [comment]
@mtrmac done and tests fixed into https://github.com/projectatomic/skopeo/pull/229 - can you ack this and https://github.com/projectatomic/skopeo/pull/229 ?

**Comment by runcom** [comment]
lgtm

**Comment by glestaris** [comment]
This is amazing! One less dependency to the `docker/docker` repository (https://github.com/containers/image/issues/54). We've been looking forward to dropping the `docker/docker` dependency (given how chunky it is) :)

**Comment by mtrmac** [comment]
:+1: thanks!  It is pretty amazing how much that allowed us to get rid of.

**Comment by mtrmac** [comment]
(Do fix the formatting which breaks the tests, though.)

**Comment by runcom** [comment]
> (Do fix the formatting which breaks the tests, though.)

done, I'll merge after tests

**Pull request merged**
