### PR TITLE
Writing multiple images to a single docker-archive: file

### PR DESCRIPTION
**Pull request by mtrmac**
WIP, absolutely untested, missing locking, probably incorrect about legacy metadata reuse.

### CODE REVIEW

**Comment by mtrmac** [comment]
@vrothberg filing very early for API feedback and possible testing / experimenting.

**Comment by mtrmac** [comment]
See also #998 for read+write in one PR.

**Comment by vrothberg** [comment]
Thanks, I'll test #998 and will comment there.

**Comment by mtrmac** [comment]
@vrothberg This should now be ready for review (although still basically untested). Changes since the early version:
- `docker/internal/tarfile.Writer.Finish` is now `Writer.Close`, similar to `archive.tar.Writer.Close`. There isn’t a (`Commit`,`Close`) difference like in `ImageDestination`, so it seems reasonable to just use the standard `Close` name.
- `docker/internal/tarfile.Writer` now uses a mutex to ensure the resulting stream is consistent, and in principle that allows copying images in parallel. I don’t expect much benefit from that, hence not setting `HasThreadSafePutBlob` either.
- The actual format implementation was changed much more than the earlier versions, to correctly create the legacy-format metadata (for images that share layers but differ in configs).

**Comment by rhatdan** [comment]
Amazing work @mtrmac LGTM

**Comment by henning-schild** [comment]
Can anyone point me to docs on how to actually use that with `skopeo` or `buildah` or any other tool really. I have multiple images and am trying to merge them into one repo image to deduplicate layers and save cost on storage and download.

**Comment by henning-schild** [comment]
Thanks. I really do not want to know the details, just found this and thought it might be a good place to ask which of the many container tools actually uses that interface. I will take that pointer to podman and just hope that the version i can get can do that.

**Pull request merged**
