### PR TITLE
remove empty .gitignore

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@mtrmac do we need .gitignore at all here? I'll remove it otherwise if we don't need it _now_

**Comment by mtrmac** [comment]
Better no file than an empty file, but either is fine with me. :+1:

**Comment by runcom** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/containers/image/pull-request/7/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=containers/image)

**Comment by mtrmac** [comment]
:+1:

**Comment by runcom** [comment]
@mtrmac you're having fun now..... :smile:

**Pull request merged**
