### PR TITLE
Rekor+Fulcio verification in policy.json

### PR DESCRIPTION
**Pull request by mtrmac**
<s>Filing a draft for early review. **DO NOT MERGE** until there is sufficient test coverage.</s>

This seems to work in some tests. Areas I’d like early feedback on:
- Design of the new `policy.json` fields in `policy_types.go` (e.g. the design decision to create a Fulcio sub-object, because the logic for issuer/subject policies might grow to be much more complex)
- The Go API to construct policy items objects in `policy_config_sigstore.go`
- Potentially the actual verification implementations in `fulcio_cert.go` and `rekor_set.go` — primarily the tentative design decision in comments, the details of the implementation might yet change as tests uncover bugs or trigger code refactoring.

<s>(This now includes a merge commit, because a part is shared with the signing work. But for now, all of that is only visible in this PR, so please ignore that merge commit.)</s>

@vrothberg PTAL.

### CODE REVIEW

**Comment by vrothberg** [comment]
Future todo: prune dependencies.

This adds ~3MB to the Podman binary.

**Review by vrothberg — COMMENTED** [review]
Code LGTM
Couldn't spot any obvious issue

**Comment by mtrmac** [comment]
This now includes sufficient unit test coverage, and an update to the man page; ready for review and possible merging.

**Review by vrothberg — APPROVED** [review]
LGTM

**Pull request merged**
