### PR TITLE
make container tools work with go-openssl

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@mtrmac @mrunalp @rhatdan PTAL.

### CODE REVIEW

**Comment by lsm5** [comment]
hmm, seems like i need to create a module for @containers/libtrust first.

**Comment by rhatdan** [comment]
LGTM

**Comment by lsm5** [comment]
given that https://github.com/containers/skopeo/pull/718 is all green, I think this should be good to merge. @vrothberg ptal when you get the chance.

**Comment by vrothberg** [comment]
Just one last request: can we also add a replace `docker/libtrust` -> `containers/libtrust` to `go.mod`. This way, all consumers of `c/image` will inherit the change. It's just an extra security net to make sure that even transitive dependencies will all use `containers/libtrust`.

Besides that, LGTM :+1: Thanks, @lsm5 !

**Comment by mtrmac** [comment]
> Just one last request: can we also add a replace `docker/libtrust` -> `containers/libtrust` to `go.mod`? This way, all consumers of `c/image` will inherit the change. It's just an extra security net to make sure that even transitive dependencies will all use `containers/libtrust`.

https://github.com/golang/go/wiki/Modules says
> exclude and replace directives only operate on the current (“main”) module. exclude and replace directives in modules other than the main module are ignored when building the main module. The replace and exclude statements, therefore, allow the main module complete control over its own build, without also being subject to complete control by dependencies.

**Comment by mtrmac** [comment]
> given that [containers/skopeo#718](https://github.com/containers/skopeo/pull/718) is all green, I think this should be good to merge. @vrothberg ptal when you get the chance.

AFAICS #718 does not actually run the tests with the code updated by this PR.

**Comment by vrothberg** [comment]
> https://github.com/golang/go/wiki/Modules says
> 
> > exclude and replace directives only operate on the current (“main”) module. exclude and replace directives in modules other than the main module are ignored when building the main module. The replace and exclude statements, therefore, allow the main module complete control over its own build, without also being subject to complete control by dependencies.

Good catch, @mtrmac! I was convinced replacements get inherited - definitely something for the release notes to mention.

**Comment by mtrmac** [comment]
Why does this need a release note? This PR replaces one dependency with another, the callers of c/image only need to update the module and should automatically get the new one; in particular, they shouldn’t need a `replace` directive (at least for c/image; they may want it for other software that uses the original subpackage and also needs to not crash).

**Comment by vrothberg** [comment]
> Why does this need a release note? This PR replaces one dependency with another, the callers of c/image only need to update the module and should automatically get the new one; 

Imagine a transitive dependency on docker/libtrust that it outside of our immediate control. If parts of the code go through docker/libtrust and others go through c/libtrust, users might end up with unexpected surprises. 

> in particular, they shouldn’t need a `replace` directive (at least for c/image; they may want it for other software that uses the original subpackage and also needs to not crash).

Right. The replace for c/image isn't needed. Others _might_ need it which is why I think we should add a note to the release notes.

**Comment by mtrmac** [comment]
> Imagine a transitive dependency on docker/libtrust that it outside of our immediate control. If parts of the code go through docker/libtrust and others go through c/libtrust, users might end up with unexpected surprises.

The library has basically no state to speak of, and c/image uses it in a very stateless manner. I don’t expect any surprises (other than that FIPS breakage, sure).

Of course announcing that the fork is available can be useful; I was just wondering about the connection with a c/image release.

**Comment by lsm5** [comment]
@mrunalp https://github.com/containers/skopeo/pull/728 is all green with the latest c/image master + docker/libtrust -> c/libtrust replacement as @vrothberg suggested. Mind taking a look at the test failures here please, not sure if that's related with the c/libtrust change.

**Comment by lsm5** [comment]
I see the same failures on the merge commit @ https://travis-ci.org/containers/image/jobs/590019172 so hopefully it's not a blocker for this.

**Comment by mrunalp** [comment]
LGTM

**Comment by mtrmac** [comment]
@lsm5 (@mrunalp ) Per https://github.com/containers/image/pull/701#issuecomment-532107501 the `Replace` directive does not affect consumers of the library, and looking at the “downloading” lines in https://travis-ci.org/containers/skopeo/jobs/590039859 , as well as at the contents of the `skopeo/vendor` directory, skopeo continues to use the docker/libtrust library (as will all other consumers of c/image).

So, this still needs fixing, properly.

**Comment by mtrmac** [comment]
> So, this still needs fixing, properly.

#715.

**Pull request merged**
