### PR TITLE
[release-5.30] Don't abort listing tags when we encounter a digest

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Cherry Pick https://github.com/containers/image/pull/2440 then bump to v5.30.2 and finally to v5.30.3-dev

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Ugh, just after I hit publish, I realized number in my commits were off, corrected and repushed.

**Comment by mtrmac** [comment]
… and the `release-1.15` branch of Skopeo would then need a backport of https://github.com/containers/skopeo/pull/2356 ; just so that I don’t forget.

**Comment by mtrmac** [comment]
> … and the `release-1.15` branch of Skopeo would then need a backport of [containers/skopeo#2356](https://github.com/containers/skopeo/pull/2356) 

https://github.com/containers/skopeo/pull/2362

**Comment by TomSweeneyRedHat** [comment]
This is a backport to begin the fix for https://github.com/containers/skopeo/issues/2346 in the versions of container tools that use c/image v5.33.

**Comment by mtrmac** [comment]
@TomSweeneyRedHat could you update `SKOPEO_CI_BRANCH` in this PR, please? I hope the tests will pass afterwards.

Alternatively, I can do that branch update (and whatever else is necessary to make the CI pass) separately on Monday.

**Comment by TomSweeneyRedHat** [comment]
@mtrmac will do.  I've been buried in CVE fun as of late and haven't looped back.  I hope to tomorrow.

**Comment by mtrmac** [comment]
@TomSweeneyRedHat CI works after #2461 .

If you are busy with CVEs, shall I rebase/finish this and release a Skopeo fix?

**Comment by TomSweeneyRedHat** [comment]
@mtrmac I'm going crazy here?  I'm trying to change the SKOPEO_CI_BRANCH to release-1.15, but when I tried to make it a separate commit, the rebase choked.  So I just added it to the last commit here, and it's not showing?  Did you by chance push it in already?   Opps, just found https://github.com/containers/image/commit/3b525404dff4b7d4f56cba407b2ceaf0c3b90545, thanks!

**Review by mtrmac — APPROVED** [review]

**Comment by mtrmac** [comment]
Thanks!

**Pull request merged**
