### PR TITLE
release-5.5: fix docker.GetDigest docker.makeRequestToResolvedURL doc…

### PR DESCRIPTION
**Pull request by haircommander**
…ker.getExternalBlob socket leak

cherry-pick of https://github.com/containers/image/commit/05fa7577cb8647a8d56db357ebe82c37856e946d
Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
this is needed for cri-o release-1.19

**Comment by mrunalp** [comment]
LGTM
@vrothberg @rhatdan @mtrmac ptal

**Comment by TomSweeneyRedHat** [comment]
LGTM
test failures are due to further Docker rate limit issues.

**Comment by vrothberg** [comment]
> test failures are due to further Docker rate limit issues.

It also did not pass the `validate` job due to commit message.

**Comment by haircommander** [comment]
related to https://bugzilla.redhat.com/show_bug.cgi?id=1948441

**Pull request merged**
