### PR TITLE
docker-archive: read+write

### PR DESCRIPTION
**Pull request by mtrmac**
This combines #991 and #996.

### CODE REVIEW

**Comment by vrothberg** [comment]
So far it's looking good. I found some time to wire this PR into the Podman one. Writing works _very_ conveniently. Will take a look into loading and report back; presumably tomorrow.

**Comment by vrothberg** [comment]
Created a first draft based on this PR (https://github.com/containers/podman/pull/6811). It's looking pretty good so far!

**Comment by vrothberg** [comment]
@mtrmac, can you have a look at containers/podman#6811 and check if the usage of the new interfaces is as intended? Once, we're cool there, I can add tests to it and then do the vendor dance.

**Comment by mtrmac** [comment]
> @mtrmac, can you have a look at [containers/podman#6811](https://github.com/containers/podman/pull/6811) and check if the usage of the new interfaces is as intended?

Yes, looks fine.

> Once, we're cool there, I can add tests to it and then do the vendor dance.

Note that the current write implementation is not correct yet, at least it generates wrong legacy-format data for images that share layers but differ in configs.

**Comment by mtrmac** [comment]
@vrothberg This was updated based on new versions of the two constituent PRs. I assume we’ll want to review one of the PRs individually, after which I will include the extra changes from that first PR into the other one, and this integration PR will be closed without merging.

**Comment by vrothberg** [comment]
@mtrmac, I am currently combining a review of the PRs with updating the open PR in c/podman. I'll add some tests on top etc.

**Comment by mtrmac** [comment]
FWIW I do plan to actually test the code modified by these PRs sometime later today. Probably not automated tests at this point, though.

**Comment by vrothberg** [comment]
> FWIW I do plan to actually test the code modified by these PRs sometime later today. Probably not automated tests at this point, though.

Feel free to share ideas for tests in https://github.com/containers/podman/pull/6811

**Comment by mtrmac** [comment]
All of the post-merge changes in this PR have been included in #991, closing.

**Pull request closed without merging**
