### PR TITLE
Don’t load the manifest in GetSignatures if the digest is known

### PR DESCRIPTION
**Pull request by mtrmac**
If we are supplied a digested reference, use it instead of possibly fetching the manifest.  This allows using signatures which are not protected even if the manifest is, in some situations.

To ensure consistent behavior, only do this if the reference uses the `digest.Canonical` algorithm, which has been used so far.  This could be perhaps relaxed in the future.

Note that this does not promise that GetSignatures will never need authentication—e.g. for `X-Registry-Supports-Signatures` this already depends on the server, and for the sigstore lookaside authentication
support may be added in the future.

Cc: @mfojtik

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM, thanks @mtrmac 

This means that using digest as part of the image pull spec will pickup that digest without manifest retrieval, right?
Also to make sure, the manifest has to be provided in order to verify the signature still right?

**Comment by mtrmac** [comment]
> This means that using digest as part of the image pull spec will pickup that digest without manifest retrieval, right?

Yes, AFAICS.

> Also to make sure, the manifest has to be provided in order to verify the signature still right?

Yes.

**Comment by mfojtik** [comment]
@runcom lgty? need this and context to complete the signature import for 3.6.1

**Comment by runcom** [comment]
LGTM

**Comment by runcom** [comment]
@mtrmac feel free to LGTM yourself and merge

**Comment by mtrmac** [comment]
:+1:

**Pull request merged**
