### PR TITLE
use container/storage/pkg/homedir

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
This ends up pulling the docker dependency into containers/common and then into other repos.  We have both being used, and I would rather stick to the one we maintain.

**Comment by mtrmac** [comment]
Most of users of c/common are going to pull in docker/docker via c/image/transports/alltransports.ParseImageName through c/image/docker/daemon anyway, so I don’t think this is going to make any difference in that respect.

**Comment by rhatdan** [comment]
Well lets hope it does.  @vrothberg @mtrmac @TomSweeneyRedHat PTAL and Merge.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
I'll let @mtrmac or @vrothberg hit the big merge button

**Pull request merged**
