### PR TITLE
copy,refactor: split `copyOneImage` and `copyMultipleImages`

### PR DESCRIPTION
**Pull request by flouthoc**
As discussed in https://github.com/containers/image/pull/1875 it is suggested to keep the two implementation in different files since there independent complexity is increasing.

### CODE REVIEW

**Comment by flouthoc** [comment]
@mtrmac PTAL, the only callers of `copyOneImage` and `copyMultipleImage` is `func Image(` which i kept intact but we can also move parts of it to `single` and `multiple`.

**Review by mtrmac — COMMENTED** [review]
Thanks!

Please also move
- Smaller utility functions only used in the moved functions (e.g. `compareImageDestinationManifestEqual`). In particular all of the layer code that still is in `copy.go` should move to `single.go`
- Similarly, the global constants/variables that only are used in the moved functions (e.g. `compressionBufferSize`), to the same files
- `imageCopier` itself, to `single.go` (and probably all methods on `imageCopier`).
- Unit tests should move with the tested functions.

---

(If you’d like, I can prepare a PR for these moves — the choice basically depends on how it would be more convenient for you to rebase/update the other outstanding work.)

**Comment by flouthoc** [comment]
> (If you’d like, I can prepare a PR for these moves — the choice basically depends on how it would be more convenient for you to rebase/update the other outstanding work.)

@mtrmac Sure sounds good to me, I'll rebase on top of these changes.

**Comment by mtrmac** [comment]
> (If you’d like, I can prepare a PR for these moves

https://github.com/containers/image/pull/1878

**Comment by mtrmac** [comment]
#1878 was merged.

**Pull request closed without merging**
