### PR TITLE
Add all certs.d/$host/*.crt CAs instead of only the last one

### PR DESCRIPTION
**Pull request by mtrmac**
(Really should add tests as well.)

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Change LGTM.
Maybe it's a lack of tea, but I'm not seeing how the title relates to the change.  It looks like you're still getting the same certs, but now only if they've not already been retrieved.
Test case or two would be good.

**Comment by mtrmac** [comment]
> Maybe it's a lack of tea, but I'm not seeing how the title relates to the change. It looks like you're still getting the same certs, but now only if they've not already been retrieved.

The idea is supposed to be that
```go
tlsc.RootCAs = systemPool
```
overwrites the field, discarding CA certificates loaded by previous iterations of the loop.

But to be fair I haven’t actually tested that; so please hold on merging this until I write tests. This really is too important code not to have tests.

**Comment by mtrmac** [comment]
Tests added (and they do show that this change is necessary).

**Comment by runcom** [comment]
travis' complaining (???)

**Comment by mtrmac** [comment]
> travis' complaining (???)

Yes, 
https://github.com/containers/storage/pull/210#issuecomment-416671810 . I can take a look tomorrow.

**Comment by mtrmac** [comment]
👍

**Pull request merged**
