### PR TITLE
Cirrus: Use F37 CI VM Image

### PR DESCRIPTION
**Pull request by cevich**
Ref: https://github.com/containers/skopeo/pull/1821

### CODE REVIEW

**Comment by mtrmac** [comment]
It seems that Skopeo might need extra updates to make this possible:
> ```
> /var/tmp/go/src/github.com/containers/skopeo/./contrib/cirrus/runner.sh: line 120: /var/tmp/go/src/github.com/containers/image/systemtest/helpers.bash: No such file or directory
> ```

**Comment by cevich** [comment]
Right...well damn.  Okay, I'll see about that...

**Comment by cevich** [comment]
...fix: https://github.com/containers/skopeo/pull/1862

**Review by mtrmac — APPROVED** [review]
@cevich Thanks for the quick fix!

**Pull request merged**
