### PR TITLE
Bump Fedora to release 35 & Ubuntu to 21.10

### PR DESCRIPTION
**Pull request by cevich**
Depends on https://github.com/containers/skopeo/pull/1499

### CODE REVIEW

**Comment by cevich** [comment]
Rebased.

**Comment by mtrmac** [comment]
I’m sorry I have missed this, Gmail keeps the original thread subject with`[WIP]` it seems.

To confirm, this is good to merge right now, isn’t it?

**Comment by cevich** [comment]
> To confirm, this is good to merge right now, isn’t it?

Yep, should be.

**Comment by mtrmac** [comment]
Thanks!

**Pull request merged**
