### PR TITLE
alltransports: ostree is linux only

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
Please update `ostree_stub.go` in the same directory as well.

**Comment by vbatts** [comment]
updated PTAL

**Comment by vbatts** [comment]
let me just double check that a comma here means AND

**Comment by vbatts** [comment]
yea https://golang.org/pkg/go/build/#hdr-Build_Constraints carry on

**Comment by mtrmac** [comment]
The idea is that the stub is compiled in exactly when the true registration isn’t, so shouldn’t the negation of (`!containers_image_ostree_stub` and `linux`) be (`containers_image_ostree_stub` or `!linux`)?

**Comment by vbatts** [comment]
@mtrmac yea, i think you're right. Updated. PTAL

**Comment by vbatts** [comment]
@mtrmac off-topic of this PR, but similar needs to be done between `./signature/mechanism_gpgme.go` and `./signature/mechanism_openpgp.go` but there is something more tricky in that arrangement, including undefined functions like:
```
vendor/github.com/containers/image/signature/mechanism.go:48:9: undefined: newGPGSigningMechanismInDirectory
vendor/github.com/containers/image/signature/mechanism.go:56:9: undefined: newEphemeralGPGSigningMechanism
```

**Comment by mtrmac** [comment]
:+1: Thanks!

**Comment by mtrmac** [comment]
> @mtrmac off-topic of this PR, but similar needs to be done between `./signature/mechanism_gpgme.go` and `./signature/mechanism_openpgp.go`

Not exactly the same thing; GpgME can be installed on macOS (and we do use it there by default). Maybe we might want to disable GpgME on Windows, or autodetect its availability.

> but there is something more tricky in that arrangement, including undefined functions like:
> ```
> vendor/github.com/containers/image/signature/mechanism.go:48:9: undefined: newGPGSigningMechanismInDirectory
> vendor/github.com/containers/image/signature/mechanism.go:56:9: undefined: newEphemeralGPGSigningMechanism
> ```
That looks like you have disabled both of the mechanisms, which is not supported; at least one of them must be enabled.  (The `openpgp` one does not require `cgo`, so it should be an acceptable universal fallback.)

**Comment by vbatts** [comment]
i can't figure out how to get the mechanism to just choose openpgp when
building on windows. :-\

**Comment by vbatts** [comment]
updated. PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by mtrmac** [comment]
@runcom ping

**Comment by vbatts** [comment]
@runcom review please?

**Comment by runcom** [comment]
lgtm

**Pull request merged**
