### PR TITLE
v5.5.4

### PR DESCRIPTION
**Pull request by QiWang19**
Cut new version for https://github.com/containers/image/pull/1280.

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by QiWang19** [comment]
@vrothberg @mtrmac @rhatdan PTAL. Bump the version as the comment  https://github.com/containers/image/pull/1280#issuecomment-871166108 suggested.

**Review by vrothberg — COMMENTED** [review]
Can you repush the commit and correct the version to `5.5.5`?

**Review by vrothberg — APPROVED** [review]
LGTM, thanks

**Comment by QiWang19** [comment]
Just curious, why skip the 5.5.4?

**Review by mtrmac — COMMENTED** [review]
Usually what would happen is:
- A commit to drop the "-dev" suffix to get a 5.5.4 final
- (After the PR is merged, tag _that_ commit as `v5.5.4`)
- Another commit in the same PR to move to 5.5.5-dev (by bumping `VersionPatch` and restoring `VersionDev`)

but @vrothberg might have a reason to skip v5.5.4 entirely, let’s wait for him.

**Comment by vrothberg** [comment]
My bad of reviewing in a rush.  `v5.5.4` is the right version.  Bumping to `v5.5.5-dev` after SGTM.

**Comment by QiWang19** [comment]
@mtrmac @vrothberg PTAL.  Should I have these commits in separate PRs?

**Review by mtrmac — APPROVED** [review]

**Comment by mtrmac** [comment]
No, this is fine. I have tagged 5.5.4.

Thanks!

**Pull request merged**
