### PR TITLE
Revert "Unit test for golang gzip backward compatibility"

### PR DESCRIPTION
**Pull request by mtrmac**
This reverts #136 .

Already golang 1.6.3 (e.g. Fedora 24) and 1.7 (the test values) differ in gzip output, which makes development on Fedora 24 cumbersome.

To fix the gzip output, we would need to carry a forked version of the gzip compression implementation; looking at https://go.googlesource.com/go/+log/master/src/compress , the idea of following upstream changes and deciding which ones are bugfixes to backport and which ones are improvements to leave out is extremely unattractive.

And of course bugfixes which need backporting may change the output anyway; we simply can’t make a long-term promise that the compressed stream will stay unchanged with an evolving implementation.

### CODE REVIEW

**Comment by mtrmac** [comment]
@runcom @jwhonce any progress on this?

**Comment by runcom** [comment]
I'd go with this for the exact reasons you highlighted. LGTM

**Comment by mtrmac** [comment]
Oh well, a week since filing this, 23 days since the initial report, with no sign of a practical long-term solution.

:+1:

@runcom please consider merging (= giving you one more chance not to).

**Comment by runcom** [comment]
totally fine with this, we'll reiterate on this later - maybe with @jwhonce and @imcleod

**Pull request merged**
