### PR TITLE
make container tools work with go-openssl

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@mrunalp @mtrmac @rhatdan PTAL.

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by lsm5** [comment]
Travis build seems to fail because it's using go mod, but this branch isn't.

**Comment by mtrmac** [comment]
Yeah; let’s make this change on `master` first, and have it pass the tests there.

_Only afterwards_ we can, on this branch, relax the CI (the `cri-o-release-1.13` branch has disabled `test-skopeo` entirely, for example) or modify it to be more appropriate (test a podman build, ideally, I guess).

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM one CI fun is righted.

**Comment by lsm5** [comment]
PR for master branch: https://github.com/containers/image/pull/701

**Comment by mtrmac** [comment]
@lsm5 Do you plan to use the `podman-1.4.2` branch, or should I delete it?

**Pull request closed without merging**
