### PR TITLE
sysregistriesv2: Split configuration loading and merging

### PR DESCRIPTION
**Pull request by mtrmac**
This is a “rebase” of #1076 on top of #1060, but that more than doubles the scope.

### CODE REVIEW

**Comment by mtrmac** [comment]
DO NOT MERGE as is, the core of #1060 should be reviewed there.

**Review by vrothberg — COMMENTED** [review]
LGTM :+1:

**Comment by mtrmac** [comment]
@vrothberg rebased, PTAL.

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM
Is this ready to go in?  Need to remove RFC: If yes?

**Comment by mtrmac** [comment]
Yes, this is now ready for review. Thanks for the reminder.

**Comment by rhatdan** [comment]
We are ready to merge, once this passes tests.
@cevich we need to get this test suite off of travis and onto cirrus.  Travis tests are taking huge amounts of time, to start.

**Comment by cevich** [comment]
> @cevich we need to get this test suite off of travis and onto cirrus. Travis tests are taking huge amounts of time, to start.

Ahh /sigh/ yep...the wheels of Travis are only greased with dollar-bills these days.  Unfortunately for their business model, I happen to know someone who has experience performing CI-conversion rituals :grinning: 

I'll add a Jira card for this (and I think there was another repo-in-need you mentioned, no?)

**Comment by vrothberg** [comment]
> > @cevich we need to get this test suite off of travis and onto cirrus. Travis tests are taking huge amounts of time, to start.
> 
> Ahh /sigh/ yep...the wheels of Travis are only greased with dollar-bills these days. Unfortunately for their business model, I happen to know someone who has experience performing CI-conversion rituals grinning

Thank you so much, @cevich!

> I'll add a Jira card for this (and I think there was another repo-in-need you mentioned, no?)

Skopeo would be great. Although we Skopeo CI is now making use of Travis' multi-arch build feature. We may need to keep the multi-arch part in Travis for now but can move all other testing over to Cirrus.

**Comment by cevich** [comment]
> Skopeo would be great.

Ahh that's the one, thanks for the reminder @vrothberg, I'll clone the jira card for a skopeo conversion as well.

> We may need to keep the multi-arch part in Travis for now but can move all other testing over to Cirrus.

Yep, that's no problem, the two can exist at the same time w/o conflict.

**Pull request merged**
