### PR TITLE
Regenerate expired certificates

### PR DESCRIPTION
**Pull request by mtrmac**
… to fix CI.

Thanks to Jesse Rittner <rittneje@gmail.com> (@rittneje ) for preparing this in #1056.

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by mtrmac** [comment]
Actually:
- Let’s extend the lifetime of certificates to 10 years
- And update the `rejected_certs` one as well, so that we are testing trust, not just expiration.

**Comment by mtrmac** [comment]
@vrothberg PTAL again

**Review by vrothberg — COMMENTED** [review]
Ten years sound even better :) LGTM

**Pull request merged**
