### PR TITLE
Don't change dockerImageSource.Reference() if a mirror is used

### PR DESCRIPTION
**Pull request by mtrmac**
... because that value is used for signature verification.

<s>WIP because I need to figure out how to add test coverage. In the mean time, let’s at least run the Skopeo and Podman tests.</s>

### CODE REVIEW

**Comment by mtrmac** [comment]
A real-world test succeeds in https://github.com/containers/skopeo/pull/904 .

**Comment by rhatdan** [comment]
LGTM
@mrunalp @hairccommander PTAL

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by rhatdan** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1829061

**Comment by rhatdan** [comment]
@mtrmac Fix your commit message and then we can merge this.

**Comment by mtrmac** [comment]
Commit message fixed, Skopeo tests pass as well.

**Pull request merged**
