### PR TITLE
v5.10: place shortnames in `~/.cache` not `~/.config/.cache`

### PR DESCRIPTION
**Pull request by vrothberg**
In case XDG_CACHE_HOME isn't set for a rootless user, fix the fallback
location that we inteded to be `~/.cache` but while refactoring placed
it in `~/.config/.cache` instead.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan @giuseppe, we need this for 8.4.  https://github.com/containers/image/pull/1155 is the counter part for the main branch.

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
As @rhatdan opened https://github.com/containers/storage/pull/826, we may very well wait for that instead.

**Comment by vrothberg** [comment]
Updated and vendored in the new c/storage

**Comment by vrothberg** [comment]
Pinned the skopeo branch in the Makefile and also bumped the version to speed things up a bit.

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
