### PR TITLE
Issue #361 Making storage transport pluggable

### PR DESCRIPTION
**Pull request by hferentschik**
Signed-off-by: Hardy Ferentschik <hardy@hibernate.org>

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by nalind** [comment]
Looks reasonable to me.

**Comment by mtrmac** [comment]
:+1: Thanks!

**Comment by rhatdan** [comment]
@runcom PTAL

**Comment by runcom** [comment]
lgtm

**Comment by runcom** [comment]
please rebase also

**Comment by hferentschik** [comment]
> please rebase also

done

**Pull request merged**
