### PR TITLE
oci: fix typo (empyt -> empty)

### PR DESCRIPTION
**Pull request by jonboulle**

### CODE REVIEW

**Comment by williammartin** [comment]
Hi @jonboulle, for the build `.gitvalidation` target to pass you'll need to add a DCO. Thanks!

**Comment by TomSweeneyRedHat** [comment]
Change LGTM, just need to sign/DCO it.   'git commit --amend -s'

**Comment by jonboulle** [comment]
oops, fixed

**Comment by rhatdan** [comment]
LGTM

**Comment by mtrmac** [comment]
:+1: Thanks!

**Comment by mtrmac** [comment]
Can you re-push this (e.g. change the commit message) to trigger CI again, please? It seems the test happened to run in the unlucky period between merging #328 and https://github.com/projectatomic/skopeo/pull/440.

**Comment by rhatdan** [comment]
@jonboulle Could you rebase?
@runcom PTAL

**Comment by jonboulle** [comment]
rebased

**Comment by rhatdan** [comment]
@jonboulle We finally got a version of this merged.  Thanks for the PR. Sorry it took so long.

**Pull request closed without merging**
