### PR TITLE
Bump to c/storage v1.54.0 then c/image to v5.31.0 and then to v5.31.1-dev

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.   Bumping c/storage to v1.54.0 and then c/image to v5.31.0 and v5.31.1-dev.  This is in preparation for Podman v5.1

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
https://github.com/containers/storage/pull/1924 broke API and the corresponding c/image update is not yet reviewed/merged. Looking…

I guess _something_ usually goes wrong, so let’s hope this fills our quota for this week.

**Comment by TomSweeneyRedHat** [comment]
Just for easier finding, the c/image PR that's blocking, I believe, is https://github.com/containers/image/pull/2416

**Review by mtrmac — CHANGES_REQUESTED** [review]
@TomSweeneyRedHat this would probably now compile, but please wait until #2428 gets in, at least for the `TOCDigest` part.

**Review by mtrmac — APPROVED** [review]
@TomSweeneyRedHat After some rebases done by GitHub, this is just a version number bump, and LGTM.

But please double-check this after me (and then merge).

**Comment by TomSweeneyRedHat** [comment]
@mtrmac Thanks, looking through it now.

**Comment by TomSweeneyRedHat** [comment]
@mtrmac LGTM, I had to convince myself that that v1.54 bump for storage was there.

**Pull request merged**
