### PR TITLE
Use a container for CI

### PR DESCRIPTION
**Pull request by giuseppe**
This is a followup for https://github.com/containers/image/pull/279

### CODE REVIEW

**Comment by giuseppe** [comment]
@mtrmac here the PR for moving the tests in a container.  I've dropped the WIP from the title as the tests are passing now

**Comment by mtrmac** [comment]
LGTM

**Comment by giuseppe** [comment]
@runcom does this look fine to you?

**Comment by runcom** [comment]
LGTM, could you please rebase?

**Comment by giuseppe** [comment]
sure, just rebased ⬆️

**Pull request merged**
