### PR TITLE
manifest: LayerInfos: preallocate the slice

### PR DESCRIPTION
**Pull request by kolyshkin**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Review by mtrmac — COMMENTED** [review]
WDYT about `make(…, 0, len(…))` + continuing to use `append`?

I think that achieves the primary optimization goal (not over-allocating, and not calling an allocation function in the loop) without giving up on safety WRT hypothetical future logic changes — at _some_ performance cost, 2 conditional jumps per loop instead of one (sadly, per https://godbolt.org/z/Gbo98a74K , Go can optimize out the range check in `[i]`, but not the capacity check in `append`).

**Comment by kolyshkin** [comment]
> WDYT about `make(…, 0, len(…))` + continuing to use `append`?

I thought about that, but since we don't do any filtering inside the loop here I went another way.

Changed.

**Review by mtrmac — APPROVED** [review]
Thanks!

**Pull request merged**
