### PR TITLE
copy: don't lose annotations of BlobInfo

### PR DESCRIPTION
**Pull request by vrothberg**
Fixes: #694
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@vbatts, that's a fix for the BuildSourceImage script.

**Comment by vbatts** [comment]
LGTM

**Comment by vrothberg** [comment]
@mtrmac, this for #694 predates the mime type/compression changes. It's currently blocking the source-containers project. It would be great to have it in the next (hopefully soon) release.

**Comment by mtrmac** [comment]
Sure, this is a long-standing bug independent of the MIME type aspect; it’s just that the code documentation, to the limited extent it exists, needs updating — for _both_.

**Comment by vrothberg** [comment]
Added a small extension to the comments you mentioned.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
