### PR TITLE
docs/: prefix manpages with "containers-"

### PR DESCRIPTION
**Pull request by vrothberg**
Fixes: #492
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@mtrmac @rhatdan PTAL.

I did not rename `signature-protocols.md` as it's not used as a manpage. Neither did I rename `atomic-signature.md` as it already carries a prefix.

**Comment by TomSweeneyRedHat** [comment]
LGTM, but would like other head nods.

**Comment by rhatdan** [comment]
@vrothberg Could you verify that these show up in `man -k container` with this change?

**Comment by vrothberg** [comment]
> @vrothberg Could you verify that these show up in `man -k container` with this change?

Good that you asked. No, it currently does not work as it `-k/apropos` seem to only grep for the string in the manpages `# NAME` section. I need to rename it there as well to `containers-registries.conf`.

**Comment by vrothberg** [comment]
Updated:
```
docs/: prefix manpages with "containers-"

Prefix manpages with "containers-" and propagate the change into the
manpages.  Furthermore, make sure that the manpages have the NAME and
DESCRIPTION section to make them be indexed by `man -k` and `apropos`.
```

**Comment by rhatdan** [comment]
LGTM

**Comment by mtrmac** [comment]
👍 Thanks!

**Pull request merged**
