### PR TITLE
[release-5.15] Bump c/storage to v1.34.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Bump c/storage to v1.34.1 to ready for Podman 3.3

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
I repushed as 7 of the 8 tests were cancelled without an explanation and the 8th had passed...

**Comment by TomSweeneyRedHat** [comment]
@cevich any thoughts as to why these tests cancelled?

**Comment by cevich** [comment]
> @cevich any thoughts as to why these tests cancelled?

Looking...

**Comment by cevich** [comment]
...Looks like a google or inter-networking problem.  I restarted the [offending thingamabob](https://cirrus-ci.com/task/6426364535373824) and will keep an eye on it passing.  Assuming it passes, it should un-cancel and execute all the rest automatically.

**Review by mtrmac — APPROVED** [review]
LGTM.

**Comment by TomSweeneyRedHat** [comment]
@cevich, I never found such a switch, I should look over your shoulder one day to spot that.  Thanks!

**Comment by cevich** [comment]
> I should look over your shoulder

Naa, better that you retain sight in both eyes :laughing:   TBH, this was an infrastructure flake that has been very very rare (I hope).  You did the right thing pinging me.

**Pull request merged**
