### PR TITLE
Use the same HTTP client for contacting the bearer token server and t…

### PR DESCRIPTION
**Pull request by umohnani8**
…he registry

Signed-off-by: Miloslav Trmač <mitr@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
tests are green! @mtrmac @rhatdan PTAL

**Comment by rhatdan** [comment]
@umohnani8 You removed test-skopeo?  Is this going to eliminate tests with skopeo?

**Comment by umohnani8** [comment]
@rhatdan yeah because the travis is more up to date than the base commit of this branch. We just need this to be able to vendor in the CVE fixes into cri-o 1.14 without having to update a bunch of the other vendored packages. Did the same thing the in the cri-o-release-1.13 branch as well https://github.com/containers/image/pull/696

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
