### PR TITLE
docker: reuse docker/distribution registry errros

### PR DESCRIPTION
**Pull request by runcom**
Instead of that big json, reuse docker/distribution registry errors since we are already used by that in Docker. This change isn't a big deal but at least I got tests working in projectatomic/docker#200 and errors are much much nicer with skopeo:
```
$ ./skopeo inspect docker://runcom/doesnotexist
FATA[0001] manifest unknown: manifest unknown

$ ./skopeo inspect docker://asdasd
FATA[0002] unauthorized: authentication required
```
Note those errors above are the same docker print out.

This is a blocker for projectatomic/docker#200 because w/o this we don't have any way/mapping to tell docker to fallback to v1 and we end up breaking docker.

@mtrmac PTAL

@baude @aweiteka sort of related to https://github.com/projectatomic/atomic/issues/636

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@glestaris PTAL since you exported that `ErrFetchManifest` but you can now use finer grained errors from docker/distribution (and it's not pulling almost anything as dependencies)

**Comment by runcom** [comment]
skopeo's PR to fix tests https://github.com/projectatomic/skopeo/pull/232

**Comment by mtrmac** [comment]
:+1:

**Comment by glestaris** [comment]
@runcom thanks for the heads up! We got it bumpbed yesterday https://github.com/cloudfoundry/grootfs/commit/0d2ed8665305d09d01f6435bf51ef1713d698cba :)

**Pull request merged**
