### PR TITLE
sysregistriesv2: cache registries

### PR DESCRIPTION
**Pull request by vrothberg**
Cache previously loaded registries with the path to the specific config
file as the key.  Such kind of caching avoids redundantly loading the
config file.  The cache is thread safe and thus qualifies to be used
concurrently.

Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@mtrmac I updated the comment and changed error control path in GetRegistries(). Thanks for the nice review!

**Comment by mtrmac** [comment]
👍 Thanks!

**Comment by rhatdan** [comment]
@runcom PTAL and merge.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
