### PR TITLE
[5.10] backports and cut 5.10.3

### PR DESCRIPTION
**Pull request by vrothberg**
@rhatdan PTAL

I cut a new release-5.10 branch and will move the main branch to 5.11-dev.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by vrothberg** [comment]
Docker Hub rate limits :( I'll merge since we need it for the 3.0 release. The impacted tests passed.

**Comment by vrothberg** [comment]
This should have been 5.10.**2**. I'll fix that in the branch directly.

**Pull request merged**
