### PR TITLE
Cleanup API

### PR DESCRIPTION
**Pull request by runcom**
Fairly simple PR extracted from https://github.com/containers/image/pull/30

@mtrmac you already ack'ed there also. I'll fix skopeo as soon as we merge this.

### CODE REVIEW

**Comment by runcom** [comment]
lgtm

**Comment by mtrmac** [comment]
Yes, and as expected, `test-skopeo` fails. Do you have a corresponding skopeo branch with which it succeeds?

**Comment by runcom** [comment]
@mtrmac yes I have

**Comment by runcom** [comment]
@mtrmac https://github.com/projectatomic/skopeo/pull/142

**Comment by runcom** [comment]
skopeo is green with this

**Comment by mtrmac** [comment]
LGTM, thanks!

**Pull request merged**
