### PR TITLE
one commit: Fix README.md

### PR DESCRIPTION
**Pull request by I-Cat**
Fix README.md

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@I-cat, we'll need a valid title and description before we can move forward with this.

**Comment by mtrmac** [comment]
Also, please rebase the PR so that the “one commit” only contains the changes you are proposing.

**Comment by I-Cat** [comment]
> Also, please rebase the PR so that the “one commit” only contains the changes you are proposing.

>> Oh no, how do I rebase Again? I thought I had it but then github website told me to edit on the web site then it added a nother commit.

**Comment by vrothberg** [comment]
`git remote update` followed by `git pull --rebase` is what I usually do but there is a number of ways to rebase.

**Pull request closed without merging**
