### PR TITLE
Api fixes

### PR DESCRIPTION
**Pull request by runcom**
@mtrmac PTAL

* take care of adapting OCI code to image-spec
* address a comment from Docker https://github.com/docker/docker/pull/26369#discussion_r77919257

### CODE REVIEW

**Comment by runcom** [comment]
lgtm

**Comment by runcom** [comment]
@mtrmac please review and merge

**Comment by mtrmac** [comment]
I’m not _happy_ with the `s/MIME/Media/`; “MIME type” clearly refers to RFC 2046 and friends; “media type" could be anything.

Is it practical to push back?

**Comment by mtrmac** [comment]
:+1:, \*sigh*

**Comment by runcom** [comment]
fixing skopeo ...

**Comment by stevvooe** [comment]
@mtrmac They are actually called [Media Types](https://en.wikipedia.org/wiki/Media_type). I'm not sure if you've actually read [RFC2046](https://www.ietf.org/rfc/rfc2046.txt), but the title is actually "Multipurpose Internet Mail Extensions (MIME) Part Two: __Media Types__" and goes on to define a series of _Media Types_. While these can be used with MIME, there is no such thing as a "MIME Type".

The term "Media Type" is used consistently throughout the container standards and specifications.

**Comment by mtrmac** [comment]
@stevvooe Of course the RFC introducing the concept of types to MIME predates their widespread usage outside of MIME, and thus was fine with using a generic name which has a specific meaning within its own context and found it unnecessary to use a self-referential name, I stand by my opinion that on the wide internet, saying “MIME type” is specific and “media type” may be something else like a fourCC code in RIFF/MPEG containers (and using "media” to refer to filesystem tarballs is awkward).

Anyway, this has been merged.

**Pull request merged**
