### PR TITLE
Use dockerImageDestination.PutManifest in openshiftDestination.PutManifest

### PR DESCRIPTION
**Pull request by mtrmac**
Instead of manipulating an `ImageStreamMapping` and having to do exactly what OpenShift does, just use the Docker Registry API and let the server side deal with that.

This fixes “unexpected end of JSON input” when uploading schema2 manifests (because we didn’t also include the config object), and should resolve https://github.com/projectatomic/skopeo/issues/208 (by using the existing code on the server side)

### CODE REVIEW

**Comment by miminar** [comment]
LGTM

**Comment by miminar** [comment]
See related OpenShift issue: https://github.com/openshift/origin/issues/11012

**Comment by runcom** [comment]
lgtm

**Comment by mtrmac** [comment]
So, this fails because a tag is optional in the Docker Registry API, but mandatory in OpenShift (ultimately via https://github.com/openshift/origin/blob/master/pkg/image/api/validation/validation.go#L246 ). Ideally we would want #88 , but let’s go with the very minimal pseudo-fix: https://github.com/containers/image/pull/98 , will make this dependent on it.  (mtrmac/skopeo:integrate-all-the-things is alraedy using the minimal fix from #98 ).

**Comment by mtrmac** [comment]
:+1:

**Pull request merged**
