### PR TITLE
Tidy up old modules and remove broken reference

### PR DESCRIPTION
**Pull request by dustin-decker**
I ran `go mod tidy` to clean up old modules references.

An missing reference for an older version of `gpgme` is causing upstream repo builds to fail: https://github.com/containers/buildah/issues/2096

```
go: github.com/containers/image/v5@v5.1.0 requires
	github.com/mtrmac/gpgme@v0.0.0-20170102180018-b2432428689c: invalid version: unknown revision b2432428689c
```

### CODE REVIEW

**Comment by dustin-decker** [comment]
I'm not sure why DCO validation is failing. My commit is signed.

**Comment by rhatdan** [comment]
The PR is not signed.  Execute the following.

```
git commit -a --amend -s
git push --force
```

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM once signed and happy tests.

**Comment by dustin-decker** [comment]
Ah, commit was GPG signed but not _signed off._ Fixed.

**Comment by mtrmac** [comment]
Reading https://github.com/containers/buildah/issues/2096 , I don’t think this is going to fix that problem.

That problem relates to the v5.1.0 version of c/image, and whatever we do here, on the master branch, is not going to fix it.

The problem is that c/image v5.1.0 refers to commit b2432428689c of mtrmac/gpgme, and I have force-pushed to that repo, making the commit dangling/unavailable. I have re-pushed it into that repository in a new branch, that should help restore the references to commit b2432428689c again.

**Comment by dustin-decker** [comment]
Yes, that's correct. This change would help fix the next release of c/image. Thanks for restoring the reference, @mtrmac.

**Comment by rhatdan** [comment]
@mtrmac Should this PR be closed or merged?

**Comment by rhatdan** [comment]
@dustin-decker Needs a rebase or to be closed.

**Comment by mtrmac** [comment]
I don’t think this is necessary. Checking e.g. Buildah commit 8aff0edda6ee76f03ca17f45b41d87851fd50fb2^ (the last one with c/image 5.1.0), `rm -rf vendor && go mod vendor` now works fine for me.

**Pull request closed without merging**
