### PR TITLE
oci: override all mime types

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
The manifest seems correct but layers and config mime types are wrong, this patch fixes this.
```
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.oci.image.manifest.v1+json",
	"config": {
		"digest": "sha256:f9873d530588316311ac1d3d15e95487b947f5d8b560e72bdd6eb73a7831b2c4",
		"mediaType": "application/octet-stream",
		"size": 1771
	},
	"layers": [{
		"digest": "sha256:7c91a140e7a1025c3bc3aace4c80c0d9933ac4ee24b8630a6b0b5d8b9ce6b9d4",
		"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
		"size": 72873635
	}],
	"annotations": null
}
```

**Comment by runcom** [comment]
lgtm @mtrmac PTAL

**Comment by runcom** [comment]
confirmed skopeo with this patch works and the generated OCI manifest is now correct:
```
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.oci.image.manifest.v1+json",
	"config": {
		"digest": "sha256:2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749",
		"mediaType": "application/vnd.oci.image.serialization.config.v1+json",
		"size": 1459
	},
	"layers": [{
		"digest": "sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f",
		"mediaType": "application/vnd.oci.image.serialization.rootfs.tar.gzip",
		"size": 667590
	}],
	"annotations": null
}
```

**Comment by mtrmac** [comment]
LGTM

**Pull request merged**
