### PR TITLE
Update and rename the import for logrus v1.0.0

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
Mmm not sure why ci failed

**Comment by TomSweeneyRedHat** [comment]
The changes LGTM, like @runcom I'm not sure what's going on CI wise.

**Comment by TomSweeneyRedHat** [comment]
In case you didn't see this, I just ran into this similar containerd update.  They went to v1.0.1, not v1.0.  They too are having build issues it looks like.  https://github.com/containerd/containerd/pull/1252/files

**Comment by mtrmac** [comment]
This looks like `gofmt` failing, because after the rename the import list is no longer ASCII-betically sorted.

**Comment by mrunalp** [comment]
Updated.

**Comment by mtrmac** [comment]
@mrunalp Thanks; the tests are failing because this breaks the use in skopeo. Can you follow the last section in https://github.com/projectatomic/skopeo/blob/master/README.md#dependencies-management , please ?

**Comment by mrunalp** [comment]
@mtrmac I have created https://github.com/projectatomic/skopeo/pull/388

**Comment by rhatdan** [comment]
We have to get this one moving, since changeing the logrus support in containers/image is blocking us from upgrading containers/storage in crio.

**Comment by mtrmac** [comment]
:+1: pending tests.

**Comment by runcom** [comment]
LGTM (needs rebase also)

**Comment by mrunalp** [comment]
Rebased

**Comment by runcom** [comment]
Tests green here https://github.com/projectatomic/skopeo/pull/388#issuecomment-319447020, merging

**Pull request merged**
