### PR TITLE
v5.5.3

### PR DESCRIPTION
**Pull request by vrothberg**
Cut a new release for https://github.com/containers/image/pull/1210.

@haircommander @rhatdan @TomSweeneyRedHat PTAL

### CODE REVIEW

**Comment by vrothberg** [comment]
`validate` is still failing but will turn green once this is merged.

**Comment by haircommander** [comment]
LGTM, thanks @vrothberg

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
> `validate` is still failing but will turn green once this is merged.

merging based on this comment.

**Pull request merged**
