### PR TITLE
Update to image-spec 1.0.0

### PR DESCRIPTION
**Pull request by mtrmac**
This includes #310 to pass tests on my machine; I will rebase after #310 is merged.

### CODE REVIEW

**Comment by mtrmac** [comment]
@rhatdan FYI

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests.

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM 
Can we get this merged?

**Comment by runcom** [comment]
@mtrmac can you LGTM and get this merged?

**Comment by runcom** [comment]
I've also already merged https://github.com/projectatomic/skopeo/pull/377

**Comment by mtrmac** [comment]
:+1:

**Pull request merged**
