### PR TITLE
Switch to github.com/etcd-io/bbolt

### PR DESCRIPTION
**Pull request by vrothberg**
github.com/boltdb/bolt is no longer maintained.

Fixes: #560
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
This build will fail as Skopeo master does not yet vendor the new dep. I opened a PR for that which is already green https://github.com/containers/skopeo/pull/628.

@mtrmac @rhatdan @mrunalp PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, once tests are happy.
I'm assuming similar change for Podman incoming?

**Comment by vrothberg** [comment]
@mtrmac we hit the gpgme panic again.

**Comment by vrothberg** [comment]
Restarted Travis. Noe that the integration tests will still break.

**Comment by vrothberg** [comment]
> I'm assuming similar change for Podman incoming?

Yes, we need this for Podman as well (Cc @mheon).

**Comment by vrothberg** [comment]
> go build "-buildmode=pie" -ldflags "-X main.gitCommit=81c5e94850e1150f9d403a8031cb092768ac08a2" -gcflags "" -tags "btrfs_noversion libdm_no_deferred_remove containers_image_openpgp" -o skopeo ./cmd/skopeo
vendor/github.com/containers/image/pkg/blobinfocache/boltdb/boltdb.go:12:2: cannot find package "github.com/etcd-io/bbolt" in any of:

Now, we're good to merge. Once this PR is in, we can revendor in Skopeo and unblock CI.

**Comment by mheon** [comment]
@vrothberg So long as we do a c/image revendor with this patch at the same time, this SGTM for podman as well (I don't want to have an intermediate state where we vendor both bbolt and bolt)

**Pull request merged**
