### PR TITLE
image: guard against config being nil

### PR DESCRIPTION
**Pull request by runcom**
ref https://github.com/projectatomic/skopeo/issues/436

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by runcom** [comment]
LGTM @mtrmac PTAL

**Comment by mtrmac** [comment]
:+1:

I wouldn’t mind having tests for this, but that would turn 3-liners into several times that.

**Pull request merged**
