### PR TITLE
Add support for non-seekable files in docker-archive: sources

### LINKED ISSUE #1317: Support non-seekable files in docker-archive: sources
I have a use case where I am being sent on the fly a tarball which I want to add to a docker registry without saving it on disk.

Also not sure if it's supported, but if I have a tarball with multiple images, can I tell skopeo which of them I want to use ? something like tarball:a.tar:redis:latest or so ?

### PR DESCRIPTION
**Pull request by mtrmac**
Fixes #1317 .

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Fixing > 3 year old issues, nice.

**Comment by louisblin** [comment]
Great to hit an issue / limitation and discover it was just addressed - thanks!

**Pull request merged**
