### PR TITLE
Release v4.0.0

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by vrothberg** [comment]
LGTM
When cutting the release/tagging, can you generate a changelog? `$ git log --no-merges --format="  * %s" v3.0.3..b49a0b7` should spit out the list.

**Comment by vrothberg** [comment]
@umohnani8 FYI

**Comment by rhatdan** [comment]
@vrothberg Sure.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by lsm5** [comment]
LGTM (going by @vrothberg's comment that this can be vendored into libpod).

**Comment by vrothberg** [comment]
Currently trying to get `c/image@master` in libpod downgrades buildah to v1.9.0. Not yet sure why.

**Comment by vrothberg** [comment]
I guess we first need to update buildah, then libpod.

**Comment by vrothberg** [comment]
@rhatdan @mtrmac we need to get https://github.com/containers/image/pull/706 in to fix the buildah issue.

**Comment by vrothberg** [comment]
@rhatdan, in it's current form it does _not_ fix the buildah issue.

**Comment by mtrmac** [comment]
> Currently trying to get `c/image@master` in libpod downgrades buildah to v1.9.0. Not yet sure why.

See https://github.com/containers/libpod/pull/4165#issuecomment-537223255 and follow-ups.

**Pull request merged**
